import { useState, useEffect, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Session={session_id:string;trace_id:string;task:string;created_at:number;intent:{goal:string;allowed_effects:string[];allowed_scopes:string[]}};
type Event={event_id:string;event_type:string;span_id:string;timestamp:number;action?:{tool:string;resource:string};decision?:{decision:string;reason_codes:string[]};source_type?:string;[key:string]:unknown};
type Trace={events:Event[];nodes:{id:string;kind:string;label:string;event:Event}[];edges:{source:string;target:string;kind:string}[]};
type Approval={approval_id:string;expires_at:number;result:{action:{action_id:string;tool:string;resource:string;args_hash:string;effects:string[]};decision:{reason_codes:string[]}}};
type Status={version:string;executions:number;pending_approvals:number;actions:Record<string,number>;audit_degraded:boolean;sandbox_available:boolean;detector:string;demo:boolean;policy_version:string};
type Report={name:string;kind:string;generated_at?:string;summary?:Record<string,unknown>;limits?:string[]};
const tabs=['安全事件','动作审批','来源关系','评测报告'];
const names:Record<string,string>={SESSION_CREATED:'任务已授权',CONTEXT_SCANNED:'上下文已扫描',TOOL_CANDIDATE:'候选动作',TOOL_DECISION:'策略决策',TOOL_EXECUTING:'工具执行',TOOL_RESULT:'执行结果',APPROVAL_PENDING:'等待审批',APPROVAL_GRANTED:'审批通过',APPROVAL_DENIED:'审批拒绝',MEMORY_QUARANTINED:'记忆已隔离'};
const stamp=(n:number)=>new Date(n*1000).toLocaleTimeString('zh-CN',{hour12:false});
function Shield(){return <svg width="26" height="30" viewBox="0 0 26 30" fill="none" aria-hidden="true"><path d="M13 2 24 6v9c0 6-7 11-11 13C9 26 2 21 2 15V6Z" stroke="currentColor" strokeWidth="2"/><path d="m7 14 4 4 8-9" stroke="currentColor" strokeWidth="2"/></svg>}
function App(){
 const [token,setToken]=useState(''),[draftToken,setDraftToken]=useState(''),[tab,setTab]=useState(0),[status,setStatus]=useState<Status|null>(null),[sessions,setSessions]=useState<Session[]>([]),[selected,setSelected]=useState(''),[trace,setTrace]=useState<Trace|null>(null),[approvals,setApprovals]=useState<Approval[]>([]),[detail,setDetail]=useState<unknown>(null),[reports,setReports]=useState<Report[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState(''),[showNew,setShowNew]=useState(false),[showTool,setShowTool]=useState(false),[tool,setTool]=useState('fs.read'),[args,setArgs]=useState('{"path":"README.md"}');
 const api=useCallback(async(path:string,body?:unknown,method='POST')=>{const r=await fetch('/api'+path,{headers:{'Authorization':'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{method,body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'请求失败');return data},[token]);
 const refresh=useCallback(async()=>{if(!token)return;const [s,list,a]=await Promise.all([api('/status'),api('/sessions'),api('/approvals')]);setStatus(s);setSessions(list);setApprovals(a);if(selected){const t=await api('/traces/'+selected);setTrace(t)}},[api,token,selected]);
 useEffect(()=>{let live=true;const run=()=>refresh().catch(e=>{if(live)setError(e.message)});run();const id=setInterval(run,2500);return()=>{live=false;clearInterval(id)}},[refresh]);
 useEffect(()=>{if(!selected&&sessions.length)setSelected(sessions[0].trace_id)},[sessions,selected]);
 useEffect(()=>{if(token&&tab===3)api('/reports').then(setReports).catch(e=>setError(e.message))},[tab,token,api]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function demo(name:string){await act(async()=>{const data=await api('/demo/'+name,{});setSelected(data.trace_id);setTab(name==='approval'?1:0)})}
 const current=sessions.find(s=>s.trace_id===selected);
 const events=trace?.events??[];
 const decisions=events.filter(e=>e.decision);
 if(!token)return <main className="login"><div className="login-brand"><Shield/><span>AgentSentry <small>意链盾</small></span></div><div className="login-card"><span className="eyebrow">AGENT SECURITY WORKSPACE</span><h1>让每一个动作<br/>都有可信边界。</h1><p>连接本地安全网关，查看执行证据并审批任务变更。</p><form onSubmit={async e=>{e.preventDefault();setError('');try{const r=await fetch('/api/me',{headers:{Authorization:'Bearer '+draftToken}});if(!r.ok)throw new Error('令牌无效，请使用操作员令牌');const me=await r.json();if(me.role!=='operator')throw new Error('控制台需要操作员令牌');setToken(draftToken);setDraftToken('')}catch(err){setError((err as Error).message)}}}><label htmlFor="token">操作员访问令牌</label><input id="token" type="password" autoComplete="off" value={draftToken} onChange={e=>setDraftToken(e.target.value)} placeholder="粘贴 operator.token 中的令牌" required/><button className="primary" type="submit">连接控制台 <span>→</span></button></form>{error&&<div role="alert" className="error">{error}</div>}<small>令牌仅保存在当前页面内存中。刷新后需要重新登录。</small></div><footer>EXECUTION GUARD · POLICY · PROVENANCE</footer></main>;
 return <div className="app"><aside className="sidebar"><div className="brand"><Shield/><div>AgentSentry<small>意链盾 · 安全控制台</small></div></div><div className="workspace-label">WORKSPACE</div><nav>{tabs.map((t,i)=><button key={t} className={tab===i?'nav active':'nav'} onClick={()=>setTab(i)}><span className="nav-icon">{['◈','✓','⌘','▥'][i]}</span>{t}{i===1&&approvals.length>0&&<b>{approvals.length}</b>}</button>)}</nav><div className="session-title">最近任务 <button aria-label="新建任务" onClick={()=>setShowNew(true)}>＋</button></div><div className="session-list">{sessions.slice(0,10).map(s=><button className={s.trace_id===selected?'session selected':'session'} onClick={()=>{setSelected(s.trace_id);setTab(0)}} key={s.session_id}><span>{s.task}</span><small>{stamp(s.created_at)} · {s.intent.goal}</small></button>)}{!sessions.length&&<p className="muted">尚未创建任务</p>}</div><div className="sidebar-bottom"><span className={'dot '+(status?.audit_degraded?'red':'')}/><span>{status?.audit_degraded?'审计降级':'本地网关已连接'}<small>5090 · {status?.version}</small></span><button onClick={()=>{setToken('');setStatus(null);setTrace(null)}} aria-label="退出">↪</button></div></aside><main className="main"><header><div className="breadcrumb">工作空间 <span>/</span> {tabs[tab]}</div><div className="header-right"><span className="pill">{status?.demo?'隔离演示环境':'受控运行环境'}</span><span className="avatar">OP</span></div></header><section className="content"><div className="page-title"><div><div className="eyebrow">{['LIVE SECURITY OVERVIEW','HUMAN APPROVAL','OBSERVED PROVENANCE','VERIFIABLE RESULTS'][tab]}</div><h1>{tabs[tab]}</h1><p>{['从上下文到工具执行，跟踪每一次安全决策。','审批仅对当前动作、参数和资源版本有效。','区分实际数据引用与上下文暴露，追踪风险来源。','展示实测证据与尚未完成的验收项。'][tab]}</p></div><button className="primary compact" onClick={()=>setShowNew(true)}>＋ 新建任务</button></div>{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}<div className="stats"><Stat title="实际工具执行" value={status?.executions??0} sub="来自执行账本"/><Stat title="已阻断动作" value={status?.actions.blocked??0} sub="未进入下游执行" tone="red"/><Stat title="等待人工审批" value={approvals.length} sub="批准前保持暂停" tone="amber"/><Stat title="执行隔离" value={status?.sandbox_available?'已就绪':'不可用'} sub="chroot · UID · seccomp" tone="green"/></div>
 {tab===0&&<><div className="demo-strip"><div><b>验证防护链路</b><small>使用合成凭据与隔离仓库生成真实事件</small></div><div className="demo-buttons">{[['issue','Issue 注入'],['secret','敏感数据外发'],['approval','单次审批'],['memory','记忆污染']].map(([n,t])=><button disabled={busy} key={n} onClick={()=>demo(n)}>{t} ↗</button>)}</div></div><div className="panel"><div className="panel-title"><div><h2>事件时间线</h2><small>{current?.task??'选择演示场景或创建第一个任务'}</small></div><div className="toolbar"><span className="live"><i/>实时同步</span><button disabled={!current} onClick={()=>setShowTool(true)}>提交动作</button></div></div>{events.length?<div className="table-scroll"><table><thead><tr><th>时间</th><th>事件</th><th>动作 / 来源</th><th>决策 / 状态</th><th>证据</th></tr></thead><tbody>{[...events].reverse().map(e=><tr key={e.event_id} onClick={()=>setDetail(e)} tabIndex={0} onKeyDown={k=>k.key==='Enter'&&setDetail(e)}><td className="mono muted">{stamp(e.timestamp)}</td><td>{names[e.event_type]||e.event_type}</td><td className="mono resource">{e.action?.tool||e.source_type||'—'}<small>{e.action?.resource||''}</small></td><td>{e.decision?<Badge value={e.decision.decision}/>:<span className="muted">{String(e.status||'已记录')}</span>}</td><td><button className="text-button" onClick={()=>setDetail(e)}>查看 ↗</button></td></tr>)}</tbody></table></div>:<Empty title="暂无安全事件" text="运行上方场景，观察候选动作如何通过策略门控。"/>}<div className="panel-footer"><span>{events.length} 条事件 · {decisions.length} 次决策</span><span>规则版本 {status?.policy_version?.slice(0,10)}</span></div></div></>}
 {tab===1&&<div className="panel"><div className="panel-title"><h2>待审批队列 <span className="count">{approvals.length}</span></h2><span className="muted">过期或资源变化后需重新提交</span></div>{approvals.map(a=><div className="approval-card" key={a.approval_id}><div className="approval-heading"><Badge value="ASK"/><h3>{a.result.action.tool}</h3><small>有效至 {stamp(a.expires_at)}</small></div><p className="mono">{a.result.action.resource}</p><p className="muted">{a.result.decision.reason_codes.join(' · ')}</p><div className="approval-meta"><span>副作用：{a.result.action.effects.join(', ')}</span><span>参数指纹：{a.result.action.args_hash.slice(0,16)}</span></div><div className="approval-actions"><button onClick={()=>act(async()=>setDetail(await api('/actions/'+a.result.action.action_id+'/preview')))}>审阅完整动作</button><button disabled={busy} onClick={()=>act(()=>api('/approvals',{approval_id:a.approval_id,approve:false}))}>拒绝</button><button className="primary" disabled={busy} onClick={()=>act(async()=>{const r=await api('/approvals',{approval_id:a.approval_id,approve:true});setDetail(r)})}>批准本次动作</button></div></div>)}{!approvals.length&&<Empty title="没有等待审批的动作" text="命中 ASK 的动作会暂停，并在这里等待操作员处理。"/>}</div>}
 {tab===2&&<div className="panel"><div className="panel-title"><div><h2>来源关系图</h2><small>{current?.task||'尚未选择任务'}</small></div><button disabled={!trace} onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(trace,null,2)],{type:'application/json'}));a.download='trace.json';a.click();URL.revokeObjectURL(a.href)}}>导出证据</button></div><div className="graph-legend"><span>━━ 调用关系</span><span className="flow">━━ 显式数据引用</span><span>┄┄ 上下文暴露</span></div>{trace&&trace.nodes.length?<Graph trace={trace} onSelect={setDetail}/>:<Empty title="暂无来源图" text="每个上下文和候选动作都会形成可检查的证据节点。"/>}<p className="graph-note">关系来自网关可观察的调用与引用，不代表模型内部思考过程。</p></div>}
 {tab===3&&<><div className="report-notice"><b>验收状态与开发进度分开记录</b><p>工程测试通过不等于公开基准达标。未运行的检测 F1、攻击成功率和七天稳定性不会显示为通过。</p></div>{reports.length?reports.map(r=><div className="panel report" key={r.name}><div className="panel-title"><h2>{r.name}</h2><span className="pill">{r.kind}</span></div><pre>{JSON.stringify(r.summary,null,2)}</pre>{r.limits?.map(l=><p className="muted" key={l}>{l}</p>)}</div>):<Empty title="尚无已发布的测试报告" text="完成验收命令后，报告会随工程文档一起更新。"/>}</>}
 <footer className="main-footer"><span>AgentSentry / 意链盾</span><span>CPU 策略路径 · {status?.detector} · 单操作员部署</span></footer></section></main>
 {detail!==null&&<div className="overlay" onClick={()=>setDetail(null)}><section className="drawer" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" aria-label="事件证据"><div className="panel-title"><h2>完整证据</h2><button aria-label="关闭证据" onClick={()=>setDetail(null)}>✕</button></div><p className="muted">敏感文本已脱敏，原始动作参数仅保存在服务端加密记录中。</p><pre>{JSON.stringify(detail,null,2)}</pre></section></div>}
 {(showNew||showTool)&&<div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();act(async()=>{if(showNew){const s=await api('/sessions',{task});setSelected(s.trace_id);setTask('');setShowNew(false)}else{if(!current)return;const r=await api('/tools/call',{session_id:current.session_id,tool,arguments:JSON.parse(args),idempotency_key:crypto.randomUUID()});setDetail(r);setShowTool(false)}})}}><div className="panel-title"><h2>{showNew?'创建授权任务':'提交候选动作'}</h2><button type="button" aria-label="关闭" onClick={()=>{setShowNew(false);setShowTool(false)}}>✕</button></div>{showNew?<><label htmlFor="task">用户任务</label><textarea id="task" value={task} onChange={e=>setTask(e.target.value)} placeholder="例如：审查 src 目录中的代码，不要推送或外发" required/><small>默认范围为隔离演示仓库。任务文本决定已授权和待确认的副作用。</small></>:<><label htmlFor="tool">工具名称</label><select id="tool" value={tool} onChange={e=>{setTool(e.target.value);setArgs(({ 'fs.read':'{"path":"README.md"}','fs.write':'{"path":"review.md","content":"Review complete"}','http.request':'{"url":"https://unknown.example.test/report","body":"Public report"}','exec.python':'{"code":"print(2 + 3)"}','git.status':'{}','git.push':'{"branch":"review"}','agent.delegate':'{"task":"review code"}','memory.write':'{"name":"note","content":"A public note"}'} as Record<string,string>)[e.target.value])}}>{['fs.read','fs.write','http.request','exec.python','git.status','git.push','agent.delegate','memory.write'].map(t=><option key={t}>{t}</option>)}</select><label htmlFor="args">动作参数（JSON）</label><textarea id="args" className="mono" value={args} onChange={e=>setArgs(e.target.value)}/></>}<button disabled={busy} className="primary" type="submit">{busy?'处理中…':showNew?'创建任务':'提交至策略网关'}</button></form></div>}
 </div>
}
function Stat({title,value,sub,tone=''}:{title:string;value:string|number;sub:string;tone?:string}){return <div className="stat"><span>{title}</span><strong className={tone}>{value}</strong><small>{sub}</small></div>}
function Badge({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}><i/>{value}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><span>◇</span><h3>{title}</h3><p>{text}</p></div>}
function Graph({trace,onSelect}:{trace:Trace;onSelect:(v:unknown)=>void}){const nodes=trace.nodes;const positions=new Map(nodes.map((n,i)=>[n.id,{x:24+(i%3)*290,y:22+Math.floor(i/3)*105}]));const height=Math.max(250,Math.ceil(nodes.length/3)*105+30);return <div className="graph"><svg role="img" aria-label="事件来源关系图" viewBox={`0 0 900 ${height}`}><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#b6bfcc"/></marker></defs>{trace.edges.map((e,i)=>{const a=positions.get(e.source),b=positions.get(e.target);if(!a||!b)return null;return <path key={i} d={`M${a.x+130},${a.y+62} C${a.x+130},${a.y+90} ${b.x+130},${b.y-25} ${b.x+130},${b.y}`} fill="none" stroke={e.kind==='data_flow'?'#189880':'#c7ced8'} strokeDasharray={e.kind==='context_exposure'?'4 4':undefined} markerEnd="url(#arrow)"/>})}{nodes.map(n=>{const p=positions.get(n.id)!;return <g key={n.id} transform={`translate(${p.x},${p.y})`} onClick={()=>onSelect(n.event)} tabIndex={0} onKeyDown={e=>e.key==='Enter'&&onSelect(n.event)} role="button" aria-label={n.label}><rect width="260" height="64" rx="9" fill="white" stroke={n.event.decision?.decision==='BLOCK'?'#efb6b2':'#d9dee7'}/><text x="14" y="25" fontSize="13" fill="#283548">{n.label.length>25?n.label.slice(0,24)+'…':n.label}</text><text x="14" y="46" fontSize="10" fill="#8791a2">{n.event.decision?.decision||n.id.slice(0,26)}</text></g>})}</svg></div>}
createRoot(document.getElementById('root')!).render(<App/>);
